### ISSUE TITLE
Y it no work?

### ISSUE THREAD

**Issue by mobotsar** [primevibetime/ok-then#1]
I see buttons; I click them. Window opens (uwu), but no hentai appears. **Why no hentai appear!?**

For real tho, it's not working. Fedora 34, amd64.

**Comment by primevibetime** [comment]
> I see buttons; I click them. Window opens (uwu), but no hentai appears. **Why no hentai appear!?**
> 
> For real tho, it's not working. Fedora 34, amd64.

it takes a second for the hentai to load in, if its a valid link. only the top button works right now tho, the "make new hentai" button is less than functional lol

**Comment by mobotsar** [comment]
Epic. I've got it working now.
